export enum TransactionType {
  ORDER_PAYMENT = 'ORDER_PAYMENT',
  REFUND = 'REFUND',
  COUPON_DISCOUNT = 'COUPON_DISCOUNT',
  SHIPPING_CHARGE = 'SHIPPING_CHARGE',
  TAX_COLLECTION = 'TAX_COLLECTION',
  SUPPLIER_PAYMENT = 'SUPPLIER_PAYMENT',
  EXPENSE = 'EXPENSE',
  ADJUSTMENT = 'ADJUSTMENT',
}
