export enum PromotionType {
  PRODUCT_DISCOUNT = 'PRODUCT_DISCOUNT',
  CATEGORY_DISCOUNT = 'CATEGORY_DISCOUNT',
  CART_DISCOUNT = 'CART_DISCOUNT',
  BUY_X_GET_Y = 'BUY_X_GET_Y',
  FLASH_SALE = 'FLASH_SALE',
}
