export enum AuditActionType {
  STOCK_IN = 'STOCK_IN',
  STOCK_OUT = 'STOCK_OUT',
  ADJUSTMENT = 'ADJUSTMENT',
  RESERVATION = 'RESERVATION',
  RELEASE = 'RELEASE',
  GOODS_RECEIPT = 'GOODS_RECEIPT',
  MANUAL_ADJUST = 'MANUAL_ADJUST',
}
