export enum CampaignType {
  PROMOTIONAL = 'PROMOTIONAL',
  ABANDONED_CART = 'ABANDONED_CART',
  FLASH_SALE = 'FLASH_SALE',
  SEASONAL = 'SEASONAL',
  NEW_ARRIVAL = 'NEW_ARRIVAL',
  CUSTOM = 'CUSTOM',
}
