export enum TicketCategory {
  ORDER_ISSUE = 'ORDER_ISSUE',
  PAYMENT_ISSUE = 'PAYMENT_ISSUE',
  SHIPPING_ISSUE = 'SHIPPING_ISSUE',
  RETURN_ISSUE = 'RETURN_ISSUE',
  REFUND_ISSUE = 'REFUND_ISSUE',
  PRODUCT_ISSUE = 'PRODUCT_ISSUE',
  ACCOUNT_ISSUE = 'ACCOUNT_ISSUE',
  OTHER = 'OTHER',
}
